# 加载器配置
modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"

# 兼容的版本范围，是加载器识别模组的关键
neoforge_version_range = "${neo_version_range}"
minecraft_version_range = "${minecraft_version_range}"

# 依赖项配置
[[dependencies.${mod_id}]]
    modId = "neoforge"
    type = "required"
    versionRange = "${neo_version_range}"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "minecraft"
    type = "required"
    versionRange = "${minecraft_version_range}"
    ordering = "NONE"
    side = "BOTH"

# 模组基本信息
[[mods]]
modId = "${mod_id}"
version = "${mod_version}"  # 注意：这里建议使用 mod_version
displayName = "${mod_name}"
description = "Mini Radar Mod for Minecraft 26.1"